name: Security Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'javascript' # Adjust based on your project's languages

      - name: Build project
        run: |
          # Add commands to build your project here
          # For example, if using npm:
          npm install
          npm run build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          output: db/results/report.sarif

      - name: List files for debugging
        run: ls -al db/results

      - name: Upload SARIF report
        uses: peter-murray/github-security-report-action@v2
        with:
          token: ${{ secrets.SECURITY_TOKEN }}
          sarifReportDir: db/results
          outputDir: /home/runner/work/VolunterHub/VolunterHub
          repository: Give-Up-Squad/VolunterHub
