name: Security Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [ 'javascript' ] # Add other languages if needed
        build-mode: [ 'automatic', 'manual' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: ${{ matrix.build-mode }}
          # Uncomment and adjust the following line if you want to specify custom queries
          # queries: security-extended,security-and-quality

      - name: Build project if manual build mode
        if: matrix.build-mode == 'manual'
        shell: bash
        run: |
          echo 'If you are using a "manual" build mode for one or more of the' \
            'languages you are analyzing, replace this with the commands to build' \
            'your code, for example:'
          echo '  make bootstrap'
          echo '  make release'
          exit 1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

      - name: List files for debugging
        run: ls -al db/results

      - name: Convert SARIF to HTML
        run: |
          npm install -g sarif-to-html
          mkdir -p db/results/html
          sarif-to-html -i db/results/report.sarif -o db/results/html/report.html

      - name: Convert HTML to PDF
        run: |
          sudo apt-get install -y wkhtmltopdf
          mkdir -p db/results/pdf
          wkhtmltopdf db/results/html/report.html db/results/pdf/report.pdf

      - name: List files for debugging (HTML and PDF)
        run: |
          ls -al db/results/html
          ls -al db/results/pdf

      - name: Upload SARIF report
        uses: peter-murray/github-security-report-action@v2
        with:
          token: ${{ secrets.SECURITY_TOKEN }}
          sarifReportDir: db/results
          outputDir: /home/runner/work/VolunterHub/VolunterHub
          repository: Give-Up-Squad/VolunterHub

      - name: Upload PDF report
        uses: actions/upload-artifact@v3
        with:
          name: pdf-reports
          path: db/results/pdf/report.pdf
