name: CodeQL Analysis and PDF Report

on:
   workflow_dispatch:

jobs:
  codeql-analysis:
    name: Perform CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write  # Necessary for uploading the results to GitHub

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize the CodeQL bundle
      uses: github/codeql-action/init@v2
      with:
        languages: 'javascript'  # Update with the languages you use

    - name: Perform CodeQL Analysis
      run: |
        codeql database create codeql-db --language=javascript --source-root=.
        codeql database analyze codeql-db --format=json --output=codeql-results.json

    - name: Format CodeQL Results
      id: format_results
      run: |
        # Extract CodeQL results and format them for the report
        jq -r '.[] | "\(.ruleId) - \(.message.text)\nFile: \(.locations[].physicalLocation.artifactLocation.uri):\(.locations[].physicalLocation.region.startLine)\n"' codeql-results.json > report.txt
        echo "Results formatted for PDF generation."

    - name: Install pandoc
      run: sudo apt-get install -y pandoc

    - name: Convert Report to PDF
      run: |
        pandoc report.txt -o codeql_report.pdf
        echo "PDF report generated."

    - name: Upload PDF Report
      uses: actions/upload-artifact@v3
      with:
        name: codeql-report
        path: codeql_report.pdf
