name: Generate Security Report

on:
  workflow_dispatch:

jobs:

  generate-report:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Generate Security Report
      uses: peter-murray/github-security-report-action@v2
      with:
        token: ${{ secrets.SECURITY_TOKEN }}
        outputDir: /home/VolunterHub
        repository: Give-Up-Squad/VolunterHub
