name: Security Report

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Security Scan
        run: |
          mkdir -p db/results
          # Replace the following line with the actual command to generate the SARIF report
          # Example: security-scan --output db/results/report.sarif
          echo '{"runs": []}' > db/results/report.sarif # This is a placeholder. Replace it with your actual security scan command.

      - name: List files for debugging
        run: ls -al db/results

      - name: Convert SARIF to HTML
        run: |
          npm install -g sarif-to-html
          mkdir -p db/results/html
          sarif-to-html -i db/results/report.sarif -o db/results/html/report.html

      - name: Convert HTML to PDF
        run: |
          sudo apt-get install -y wkhtmltopdf
          mkdir -p db/results/pdf
          wkhtmltopdf db/results/html/report.html db/results/pdf/report.pdf

      - name: List files for debugging (HTML and PDF)
        run: |
          ls -al db/results/html
          ls -al db/results/pdf

      - name: Upload SARIF report
        uses: peter-murray/github-security-report-action@v2
        with:
          token: ${{ secrets.SECURITY_TOKEN }}
          sarifReportDir: db/results
          outputDir: /home/runner/work/VolunterHub/VolunterHub
          repository: Give-Up-Squad/VolunterHub

      - name: Upload PDF report
        uses: actions/upload-artifact@v3
        with:
          name: pdf-reports
          path: db/results/pdf/report.pdf
