name: Deploy to Netlify

on:
  push:
    branches:
      - main
      
  workflow_run:
    workflows: ["SonarCloud analysis"]
    types:
     - completed 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install backend dependencies
      working-directory: connecting-kerry/app_api
      run: npm install

    - name: Install frontend dependencies
      working-directory: connecting-kerry/frontend
      run: npm install

    - name: Build frontend
      working-directory: connecting-kerry/frontend
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
      run: npm run build

    - name: Install dependencies for connecting-kerry directory
      working-directory: connecting-kerry
      run: npm install

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v3.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        publish-dir: connecting-kerry/frontend/build
        functions-dir: connecting-kerry/functions
        production-branch: main
        deploy-message: 'Deploying frontend and backend as serverless functions'
      env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_CERT: ${{ secrets.DB_CERT }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        
    - name: Display Deployment URL
      run: echo "Netlify Deployment URL - https://connectingkerry.netlify.app/"
      id: display_url
      
    - name: Set URL as Output
      run: echo "::set-output name=url::https://connectingkerry.netlify.app/"
      id: set_output

