name: Deploy to Render and Netlify

on:
  push:
    branches:
      - main

  workflow_run:
    workflows: ["SonarCloud analysis"]
    types:
      - completed

jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow == 'SonarCloud analysis' && github.event.action == 'completed'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install backend dependencies
        working-directory: connecting-kerry/app_api
        run: npm install

      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_CERT: ${{ secrets.DB_CERT }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        run: |
          curl -X POST \
            -H 'Accept: application/json' \
            -H 'Authorization: Bearer $RENDER_API_KEY' \
            -H 'Content-Type: application/json' \
            -d '{"serviceId": "srv-cq5smvmehbks73bus7eg"}' \
            https://api.render.com/v1/services/srv-cq5smvmehbks73bus7eg/deploys

  deploy-to-netlify:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_run' && github.event.workflow == 'SonarCloud analysis' && github.event.action == 'completed'
    needs: deploy-to-render

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install backend dependencies
        working-directory: connecting-kerry/app_api
        run: npm install

      - name: Install frontend dependencies
        working-directory: connecting-kerry/frontend
        run: npm install

      - name: Build frontend
        working-directory: connecting-kerry/frontend
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: npm run build

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          publish-dir: connecting-kerry/frontend/build
          production-branch: main
          deploy-message: "Deploying frontend and backend as serverless functions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
